name: pomodoropompurin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  contribution_heatmap: ^0.5.2
  syncfusion_flutter_gauges: ^32.1.21
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  flame: ^1.15.0
  freestyle_speed_dial: ^1.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/pomTimer/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500