name: pomodoropompurin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  contribution_heatmap: ^0.5.2
  syncfusion_flutter_gauges: ^33.1.44
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.2
  flame: ^1.15.0
  firebase_auth: ^6.2.0
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/pomTimer/
    - assets/images/kotatsu_sprites/
    - assets/images/floor_sprites/
    - assets/images/interior_wall_sprites/
    - assets/images/exterior_sprites/
    - assets/images/blanket_sprites/
    - assets/images/futon_sprites/
    - assets/images/refrigerator_sprites/
    - assets/images/study_table_sprites/
    - assets/images/study_chair_sprites/
    - assets/images/kitchen_sprites/
    - assets/images/ingridient_sprites/
    - assets/images/consumable_sprites/pudding/
    - assets/images/consumable_sprites/pizza/
    - assets/images/consumable_sprites/hamburg_steak/
    - assets/images/consumable_sprites/pancakes/
    - assets/images/kitchen_processors_sprites/
    - assets/images/shop_sprites/
    - assets/images/consumable_sprites/pudding/
    - assets/images/purin_sprites/
    - assets/images/character_icons/purin/
    - assets/images/character_icons/koupen/
    - assets/audio/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500