// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoC-GplKRutwUKH2OOv557h2E0ZIqGoSk',
    appId: '1:49840295676:web:3f75c1e28029d6163ad179',
    messagingSenderId: '49840295676',
    projectId: 'koupen-pppurin',
    authDomain: 'koupen-pppurin.firebaseapp.com',
    storageBucket: 'koupen-pppurin.firebasestorage.app',
    measurementId: 'G-JGXQJWJ0YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFI3B7gMVdBxFJdJmAertzj2YDi5s5VsI',
    appId: '1:361029373628:android:2efd0dbfb871e78e8e8ab9',
    messagingSenderId: '361029373628',
    projectId: 'pomodoropompurin',
    storageBucket: 'pomodoropompurin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY23MNNvFu1lbm488KVWx7yEl-9_RR9V0',
    appId: '1:361029373628:ios:259ae5f5e0f054bd8e8ab9',
    messagingSenderId: '361029373628',
    projectId: 'pomodoropompurin',
    storageBucket: 'pomodoropompurin.firebasestorage.app',
    iosBundleId: 'com.example.pomodoropompurin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY23MNNvFu1lbm488KVWx7yEl-9_RR9V0',
    appId: '1:361029373628:ios:259ae5f5e0f054bd8e8ab9',
    messagingSenderId: '361029373628',
    projectId: 'pomodoropompurin',
    storageBucket: 'pomodoropompurin.firebasestorage.app',
    iosBundleId: 'com.example.pomodoropompurin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCst5P_xly9aQQrF9xUg2pA7-0Fv8PQkN8',
    appId: '1:361029373628:web:757638f42d8a3f5c8e8ab9',
    messagingSenderId: '361029373628',
    projectId: 'pomodoropompurin',
    authDomain: 'pomodoropompurin.firebaseapp.com',
    storageBucket: 'pomodoropompurin.firebasestorage.app',
  );

}